export const mockData = {
    itinerary: {
      "2024-09-01": [
        {
            description: "Famous for sweets and snacks",
            endTime: "10:00",
            expense: 200.0,
            latitude: 23.2537,
            longitude: 77.4011,
            name: "Manohar Dairy",
            startTime: "09:00",
            type: "food",
        },
        {
            description: "Enjoy a serene boat ride on Bhopal's Upper Lake, also known as Bhojtal. It's the largest man-made lake in Asia and offers beautiful views of the city.",
            endTime: "12:00",
            expense: 200.0,
            image_url: "upper_lake.jpg",
            latitude: 23.2599,
            longitude: 77.3256,
            name: "Upper Lake Boating",
            startTime: "10:00",
            type: "activity",
        },
        {
            description: "Famous for MP's special Dal Bafla",
            endTime: "14:00",
            expense: 200.0,
            latitude: 23.2497,
            longitude: 77.4143,
            name: "Dal Bafla Restaurant",
            startTime: "13:00",
            type: "food",
        },
        {
            description: "Explore one of the largest mosques in India. Taj-ul-Masajid, meaning 'Crown of Mosques', is known for its stunning pink facade and spacious courtyard.",
            endTime: "15:30",
            expense: 0.0,
            image_url: "taj_ul_masajid.jpg",
            latitude: 23.2634,
            longitude: 77.4029,
            name: "Taj-ul-Masajid Visit",
            startTime: "14:00",
            type: "activity",
        },
        {
            description: "Famous for chaat and snacks",
            endTime: "21:00",
            expense: 150.0,
            latitude: 23.2505,
            longitude: 77.391,
            name: "Sharma Chat House",
            startTime: "20:00",
            type: "food",
        },
      ],
      "2024-09-02": [
        {
            description: "Famous for chaat and snacks",
            endTime: "10:00",
            expense: 150.0,
            latitude: 23.2505,
            longitude: 77.391,
            name: "Sharma Chat House",
            startTime: "09:00",
            type: "food",
        },
        {
            description: "Visit this multi-art center showcasing the rich tapestry of Indian arts. It houses a museum of folk and tribal art, an art gallery, and theaters.",
            endTime: "12:30",
            expense: 100.0,
            image_url: "bharat_bhavan.jpg",
            latitude: 23.2505,
            longitude: 77.391,
            name: "Bharat Bhavan Tour",
            startTime: "10:00",
            type: "activity",
        },
        {
            description: "South Indian cuisine",
            endTime: "14:00",
            expense: 250.0,
            latitude: 23.2331,
            longitude: 77.4343,
            name: "Sagar Gaire",
            startTime: "13:00",
            type: "food",
        },
        {
            description: "Visit this national museum of humankind which presents an integrated story of the evolution of man and culture with a focus on Indian civilization.",
            endTime: "17:00",
            expense: 100.0,
            image_url: "manav_sangrahalaya.jpg",
            latitude: 23.2023,
            longitude: 77.3764,
            name: "Indira Gandhi Rashtriya Manav Sangrahalaya",
            startTime: "14:00",
            type: "activity",
        },
        {
            description: "Traditional vegetarian thali",
            endTime: "21:00",
            expense: 250.0,
            latitude: 23.2336,
            longitude: 77.4027,
            name: "Rajhans Restaurant",
            startTime: "20:00",
            type: "food",
        },
      ],
      "2024-09-03": [
        {
            description: "Famous for sweets and snacks",
            endTime: "10:00",
            expense: 200.0,
            latitude: 23.2537,
            longitude: 77.4011,
            name: "Manohar Dairy",
            startTime: "09:00",
            type: "food",
        },
        {
            description: "Explore this modern Hindu temple dedicated to Laxminarayan. Known for its stunning architecture, it offers panoramic views of the city.",
            endTime: "11:00",
            expense: 0.0,
            image_url: "birla_temple.jpg",
            latitude: 23.233,
            longitude: 77.4043,
            name: "Birla Temple Visit",
            startTime: "10:00",
            type: "activity",
        },
        {
            description: "Famous for MP's special Dal Bafla",
            endTime: "14:00",
            expense: 200.0,
            latitude: 23.2497,
            longitude: 77.4143,
            name: "Dal Bafla Restaurant",
            startTime: "13:00",
            type: "food",
        },
        {
            description: "Take a guided tour around Bhopal's famous lakes. Learn about the city's history and its intricate system of man-made lakes.",
            endTime: "16:00",
            expense: 300.0,
            image_url: "bhopal_lake.jpg",
            latitude: 23.2599,
            longitude: 77.3256,
            name: "Bhopal Lake Tour",
            startTime: "14:00",
            type: "activity",
        },
        {
            description: "Famous for chaat and snacks",
            endTime: "21:00",
            expense: 150.0,
            latitude: 23.2505,
            longitude: 77.391,
            name: "Sharma Chat House",
            startTime: "20:00",
            type: "food",
        },
      ],
      "2024-09-04": [
        {
            description: "Famous for chaat and snacks",
            endTime: "10:00",
            expense: 150.0,
            latitude: 23.2505,
            longitude: 77.391,
            name: "Sharma Chat House",
            startTime: "09:00",
            type: "food",
        },
        {
            description: "Take a guided walk through Gohar Mahal, a beautiful palace built by the first woman ruler of Bhopal. Learn about the city's nawabi heritage.",
            endTime: "11:30",
            expense: 200.0,
            image_url: "gohar_mahal.jpg",
            latitude: 23.2497,
            longitude: 77.4143,
            name: "Gohar Mahal Heritage Walk",
            startTime: "10:00",
            type: "activity",
        },
        {
            description: "South Indian cuisine",
            endTime: "14:00",
            expense: 250.0,
            latitude: 23.2331,
            longitude: 77.4343,
            name: "Sagar Gaire",
            startTime: "13:00",
            type: "food",
        },
        {
            description: "Escape the city bustle with a picnic at Kerwa Dam. Enjoy the serene surroundings, go for a nature walk, or try some water activities.",
            endTime: "18:00",
            expense: 100.0,
            image_url: "kerwa_dam.jpg",
            latitude: 23.1844,
            longitude: 77.319,
            name: "Kerwa Dam Picnic",
            startTime: "14:00",
            type: "activity",
        },
        {
            description: "Traditional vegetarian thali",
            endTime: "21:00",
            expense: 250.0,
            latitude: 23.2336,
            longitude: 77.4027,
            name: "Rajhans Restaurant",
            startTime: "20:00",
            type: "food",
        },
      ],
    },
    total_expense: 3400.0,
};
  